version: '3.8'

services:
  dev-app:
    build:
      context: ./
      dockerfile: ../../build/docker/Dockerfile.dev
    container_name: nodejs-ts.dev-app
    volumes:
      - ../../:/app
    ports:
      - 8080:8080
